### ISSUE TITLE
The readme is a bit sparse

### ISSUE THREAD

**Issue by andybak** [erdem/django-admino#6]
I immediately wondered the following:

1. Does it respect all permissions correctly? 
2. I'm assuming form level validation isn't applied. How about model validation? (Is it worth printing a big warning about form validation? A naive usage of this could bypass a lot of app-level security)
3. Are inlines introspected in any way? What other ModelAdmin attributes have an effect on the API?

**Comment by erdem** [comment]
Hi @andybak 

First of all, the project is still in alpha version so because of that there are many parts need to develop.

1) Permissions are working only create endpoints at the moment.

2) REST API using admin ModelForm validation, API view serialise the JSON data for the Django model form.  

3) REST API does not support admin inlines yet.

Thanks
